### ISSUE TITLE
Link goes to the old dev forum on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html 

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#101]
In the section 
Concur Connect Callout Details

Information on how to download, install, and configure the application connector is included in Callouts > Core Concepts.

The link goes to the old dev portal 
https://developer.concur.com/node/25#co

**Comment by henryyamamoto-concur** [comment]
http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html
