### ISSUE TITLE
Function Link goes to the old dev forum on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html 

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#102]
Functions

Version 2.0: Post Attendee Search Request

Links to the old portal https://developer.concur.com/callouts/fetch-attendee/post-fetch-attendee

**Comment by henryyamamoto-concur** [comment]
Fixed with commit a7b031cac1d84ec0a3c9c9dc3b7031e96f361755
