### ISSUE TITLE
Issues with Concur Developer Forum

### ISSUE THREAD

**Issue by MyTotoro** [concur/developer.concur.com#1027]
Not sure if this is the best place to post but I'm having issues related with the Concur Developer Forum:

![image](https://cloud.githubusercontent.com/assets/3621921/25434085/f0bca460-2a58-11e7-83cc-3e604da304f5.png)

The result is:

![image](https://cloud.githubusercontent.com/assets/3621921/25434102/fd685358-2a58-11e7-9178-b6a14903802c.png)

I can't post help on the developer forum since I can't get access...

Thanks! Hope to get this sorted out as I want to incorporate concur API

**Comment by bhague1281** [comment]
@MyTotoro Apologies for the long delay on this issue. Our Discourse instance is not properly directing to the HTTPS protocol, so a temporary fix would be to take the activation URL you received in the email, and change the protocol to HTTPS. We'll be implementing a permanent fix for this soon.

**Comment by bhague1281** [comment]
Fixed by Discourse
