### ISSUE TITLE
Missing hyper link on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html 

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#103]
In the section Installation Process the following paragraph is missing a hyper link

A sample connector is available on the Sample Code page under Callouts, and details of the installation process are available at Callouts > Core Concepts > Sample Connector Procedures.

**Comment by henryyamamoto-concur** [comment]
Fixed with commit a7b031cac1d84ec0a3c9c9dc3b7031e96f361755
