### ISSUE TITLE
Missing hyper link to HTTP codes on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html 

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#104]
In the section 

Responses and Errors

Refer to the HTTP Codes page for details of the common responses and errors.

The hyper link is missing for HTTP codes.

**Comment by henryyamamoto-concur** [comment]
Fixed with commit a7b031cac1d84ec0a3c9c9dc3b7031e96f361755
