### ISSUE TITLE
Move Support to its own tab

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1107]
@elhansen748 commented on [Mon Jun 26 2017](https://github.com/concur/developer.concur.com-forms/issues/137)

Per feedback from the Partner Enablement team, it takes too many clicks for partners to enter support cases.  The ask is that we split "Support" out from "Tools and Support".  When the partner clicks the support tab, it should:

1.  Have the description on when/how to enter a support case (same info that is currently shown at this link:  https://developer.concur.com/tools-support/requesting-partner-support.html 
2.  Have info about using forums to get answers
3.  Have a link that takes the partner to the support portal to login and enter their case (same link also currently at bottom of this page:  https://developer.concur.com/tools-support/requesting-partner-support.html

**Comment by bhague1281** [comment]
Proposed solution:

- [ ] Remove some unnecessary sections (Newsletter, Recovering Passwords)
- [ ] Create new dropdown link at the top of Tools & Support, linking to "Request Support"
- [ ] Add "Request Support" to Tools & Support navigation
- [ ] Rename existing support page to something else
- [ ] On the "Request Support" page, add sections for Partner and Admin/User support

**Comment by bhague1281** [comment]
#1110
