### ISSUE TITLE
Remove Fetch Attendee Sample Connector Reference

### ISSUE THREAD

**Issue by hotslingers** [concur/developer.concur.com#1157]
On the Fetch Attendee page: https://developer.concur.com/api-reference/callouts/fetch-attendee.html

Please remove the following bullet point, there is no 'sample connector application' available.  

- Concur provides a sample connector application that the client can install on their network and customize to interface with their system of record for attendees. Concur can also customize the connector.

Reword this bullet point:
- (Optional- Professional/Premium only) The client can choose to create their own application connector using a different language, such as PHP, if preferred.

To:
- Clients can either choose to create their own application connector using PHP, Java, .NET etc or can use one of Concur Partner's Attendee Fetch applications.

**Comment by bhague1281** [comment]
Closed by #1158
