### ISSUE TITLE
Diagram missing in the oauth2-migration-best-practices

### ISSUE THREAD

**Issue by zenan-angus-wang** [concur/developer.concur.com#1213]
Instead of correct img_url = https://github.com/concur/developer.concur.com/raw/preview/api-reference/authentication/oldNewAuthComparion.png, the website uses "https://raw.githubusercontent.com/concur/developer.concur.com/preview/api-reference/authentication/newAndOldAuthComparison.png"

**Comment by bhague1281** [comment]
Diagram was not deployed to livesite. Should be showing correctly now. Note that https://preview.developer.concur.com should be viewed for any pending changes. Livesite deployments to https://developer.concur.com happen weekly.
