### ISSUE TITLE
Need ability for PE team to make an app globally available

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1225]
@elhansen748 commented on [Thu May 11 2017](https://github.com/concur/developer.concur.com-forms/issues/130)

@elhansen748 commented on [Wed Feb 08 2017](https://github.com/concur/developer.concur.com/issues/902)

Using the App creation tool on the Dev Center, Partner Enablement team needs to be able to change an application to globally available once it has been certified, so that the certified partner can signup and work with any interested customer at Concur.  An app is set to globally available by setting the "allowed_principals" value to '*'.  

Since a new secret is generated when an app is updated, the UI will need to display the new secret to the PE user, so that they can in turn provide it to the partner.

Other users besides the PE team should NOT have the ability to make an app globally available.  This means the Dev Center needs an ability to log the user in, and assign a specific Parter Enablement role to the user.  We then need to update the App Creation tool to allow the setting of "allowed principals" to "*" ONLY if the logged in user has the Partner Enablement permission.  See issue https://github.com/concur/developer.concur.com-forms/issues/134

**Comment by elhansen748** [comment]
I will enter a separate issue to Profile asking for new Dev Center-only roles to be added.  

Until that time, we should utilize the IT_Admin role.  This is a role that is only assigned to Concur employees and not clients.  If the user logged into the App Creation Tool has the IT_Admin role, we should display an "Allowed Principals" box in the UI.  Whatever is entered in that box should be written to App Management, preferably by a PATCH, so that the current app secret is retained.  Only valid UUIDs or the * symbol are acceptable principals, so we should validate that the entered value is a valid UUID or a *.

Once we add this support, we need to document this ability for the Partner Enablement team, who should be the only team needing the ability to change the "allowed principals" of an app.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
