### ISSUE TITLE
App Creation needs to support non-production entities

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1226]
@elhansen748 commented on [Mon Apr 24 2017](https://github.com/concur/developer.concur.com-forms/issues/128)

@elhansen748 commented on [Mon Mar 20 2017](https://github.com/concur/developer.concur.com/issues/961)

Not all Platform Applications are created in our Production environment.  The Partner Enablement team mainly uses Production sites, but many other teams use other environments.

We need a way to create sites in the following environments:

- [ ] Implementation
- [ ] EMEA
- [ ] EMEA Implementation
- [ ] RQA2
- [ ] RQA3
- [ ] RQA6
- [ ] RQA7
- [ ] China

The App Management endpoints for each environment can be found here:  https://github.concur.com/core/app-mgmt/wiki  

We also need a sandbox/test site in each environment so we can test the App Creation Tool for each environment.

The App Creation Tool on Dev Center should allow the user to dropdown and environment box and choose which datacenter the app they are creating should live in.  When choosing a datacenter other than US PROD, the tool should just either visually indicate the user's choice and the user fills out the fields exactly as they do for US Prod with the resulting app being created in the data center of their choice, or the tool should redirect them to the right place to create the app in the datacenter of their choice.  Whether one tool should be able to create an app in any datacenter, or whether we need a separate App Creation Tool for each datacenter is something we need to decide on.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
