### ISSUE TITLE
App Creation tool should prevent editing certified apps

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1228]
@elhansen748 commented on [Sat Apr 22 2017](https://github.com/concur/developer.concur.com-forms/issues/126)

Due to the tool having to create a new client_secret, which would break any users connected to an app, the App Creation tool should check if an app is certified, and if yes, not allow it to be edited.  Certified apps should only be edited by the App Management team, as we can edit the app using the original client_secret, thus not breaking any prior user connections.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
