### ISSUE TITLE
App Creation Tool needs to allow setting of custom claims

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1230]
@elhansen748 commented on [Fri Jun 23 2017](https://github.com/concur/developer.concur.com-forms/issues/136)

For all apps that use the "detokenizer" integration between SAP and Concur, there needs to be a custom claim set called "company".  This "company" value needs to be set to the client's company UUID, the same company UUID that should be set as the "allowed principal" of the app.  Without this custom value being set on the app, the SAP integration will fail.

The json for the custom claim looks like this:

  "com:concur:internal:CustomClaims:1.0": {
  "company": "3d9c8d0c-1f1b-44e1-85b7-ec9fa3629434"
  },

The UI should have a field called "Detokenizer Service Company UUID".  
Only a UUID should be accepted as input, not text like "Company A" or an integer such as "12345".  The field should not be required.  
No validation of the field should be done. 
If an app has this custom value set, the value for the app should be displayed in the UI so the logged in user can see the value.  If no value is returned, the field should just be blank.
The user should be able to modify the value if they choose, and the updated value they entered should be set for their app.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
