### ISSUE TITLE
App creation tool needs to support "legacyId"

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1231]
@elhansen748 commented on [Mon Apr 10 2017](https://github.com/concur/developer.concur.com-forms/issues/121)

In order to call some old connect APIs, when an an app is created a "legacyID" needs to be set.  the legacyID is the Outtask Company ID of the site that is needed for the old API calls to function.  A legacyID should also be set if a partner has an existing old-auth app and is creating a new auth app, so that we know the same partner owns both.

- [ ] A legacyID field should be added to the app creation form.  
- [ ] The legacyID field should not be required.
- [ ] No validation of the id should be done.  Assumption is the user will know and enter the correct value.  If they enter the wrong value they can edit the app and fix it.
- [ ] When a user logs in to view all their apps, if a legacyID is returned it should be displayed to the user in the UI.
- [ ] The user should be able to edit the legacyID of any app they own.

Sample of legacy id:

"com:concur:internal:product:Identifiers:1.0": {
    "legacyId": "12076"

**Comment by princemoseslive** [comment]
Fix changes pushed into the repo
