### ISSUE TITLE
Update App creation tool to pull available scopes from app management

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1261]
The App creation tool currently has a static list of scopes in a json file:  https://github.com/concur/developer.concur.com/blob/preview/app-management/data/scopes.json

App Management has released an endpoint that is the "source of truth" for all valid apps in Concur.

The app creation tool should be updated so that it reads from the app management scopes endpoint and displays the results to the user.  The app management endpoint can be found here:  https://appm-rqa3.concurasp.com/app-mgmt/v0/scopes

By switching the tool to use this endpoint, the tool will be updated automatically as soon as new scopes are added.

**Comment by elhansen748** [comment]
One other needed change.  There is a Scope value called "status", which can be set to 'public' or 'private'.  The App Creation/Management Tool should NOT return scopes with a status of 'private'.  Currently, the tool shows all apps whether the status is 'private' or 'pubic'.  Desired result is that only 'public' scopes are shown in the App Management Tool.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
