### ISSUE TITLE
Need to improve the App Creation Tool

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1262]
The App Creation Tool will become the only way for all Concur apps to be created and managed.  As it exists today, there are many use cases this tool can't handle.  We need to fix that so that the tool can meet all app creation and management needs.

**Comment by howarddierking** [comment]
dumb question, but shouldn't this issue be created in the respective _private_ repo containing the app management code?

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
