### ISSUE TITLE
XML Example Request Typo on Post Attendee Search Request

### ISSUE THREAD

**Issue by edtguy** [concur/developer.concur.com#1278]
**Note: for API troubleshooting and support questions, please use the [Concur Developer Center Forum](https://forum.developer.concur.com/).**

## New Issue Description

* **I am creating an issue for...**
  - [ ] New API reference pages
  - [x ] Formatting/text changes
  - [ ] A bug report
  - [ ] Feature request

* **What organization or team are you associated with?**

Alanda

* **What's the description of your issue?**

The XML request example at developer.concur.com/api-reference/callouts/post-fetch-attendee.markdown shows \<Custom9\> /\>. It should be \<Custom9 /\>

* **If this issue is a bug...**
  * **What are the steps to reproduce the bug?:** [Steps to reproduce bug here]
  * **Expected behavior:** [What you expected to happen]
  * **Actual behavior:** [What actually happened]

**Comment by bhague1281** [comment]
Thank you for pointing this out. Fixed in #1301
