### ISSUE TITLE
Switch logos and any brand references to SAP Concur

### ISSUE THREAD

**Issue by bhague1281** [concur/developer.concur.com#1288]
## New Issue Description

* **I am creating an issue for...**
  - [ ] New API reference pages
  - [x] Formatting/text changes
  - [ ] A bug report
  - [ ] Feature request

* **What organization or team are you associated with?**

Platform

* **What's the description of your issue?**

All Concur-branded items, such as logos and references to Concur, should be replaced with SAP Concur.

**Comment by elhansen748** [comment]
Hey @bhague1281, do you need any help with this issue?  I've had someone reach out to ask about this, so would like to get it updated soon.  Do you have the logos you need?

**Comment by bhague1281** [comment]
#1300
