### ISSUE TITLE
Add API Reference page for Travel Receipts API

### ISSUE THREAD

**Issue by brianaeng** [concur/developer.concur.com#1304]
## New Issue Description

* **I am creating an issue for...**
  - [x] New API reference pages
  - [ ] Formatting/text changes
  - [ ] A bug report
  - [ ] Feature request

* **What organization or team are you associated with?**

R&D Travel/Team Nether

* **What's the description of your issue?**

Adding documentation for Travel Receipts API -- one subpage for getting started (auth/anything necessary to use API), one subpage for overview (endpoint, schema), and one subpage for sample response

**Comment by bhague1281** [comment]
@elhansen748

**Comment by elhansen748** [comment]
Hi @brianaeng, great to hear that you are releasing a new/updated API!  Have you already see our wiki page for creating those pages?  If not, please review as there are some requirements that need to be met to have your docs on the developer site:  https://github.com/concur/developer.concur.com/wiki/Creating-API-Reference-pages

Also, I would love to hear a bit more about your new API and its intended audience.  Can you or someone on the team either send me an email with some high level details, or do a quick call?  Thanks!

**Comment by brianaeng** [comment]
@elhansen748 Yup, I'm following those instructions thanks! I've written up the API ref pages and some internal documentation so I'll slack or email you those for an overview 😄

**Comment by bhague1281** [comment]
Merged #1313
