### ISSUE TITLE
New Request API V4 documentation

### ISSUE THREAD

**Issue by cbobrie** [concur/developer.concur.com#1357]
**Note: for API troubleshooting and support questions, please use the [Concur Developer Center Forum](https://forum.developer.concur.com/).**

## New Issue Description

* **I am creating an issue for...**
  - New API reference pages

**I am creating an issue for New API reference pages

* **What organization or team are you associated with?**
Concur Request Product Management Team

* **What's the description of your issue?**
Adding the documentation for the new Request APIs v4

**Comment by haydenlam** [comment]
@charlieconcur I believe @cbobrie needs help creating a new API Reference page as detailed here:
https://github.com/concur/developer.concur.com/wiki/Creating-API-Reference-pages

**Comment by charlieconcur** [comment]
Completed with #1390.
