### ISSUE TITLE
Add corporate card to Google Search

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#154]
Get corporate card number to add to Google Search to get ad free search results.

**Comment by henryyamamoto-concur** [comment]
@rssanborn Can you provide @howarddierking with corporate card to add to the Google Search acct to eliminate ads? Thanks.

**Comment by rssanborn** [comment]
@henryyamamoto-concur @howarddierking can you add me as an admin to the site so I can set up billing?

**Comment by henryyamamoto-concur** [comment]
Accidentally closed this. 

I see Roger as an Admin on ZenHub.

**Comment by henryyamamoto-concur** [comment]
Found this on their site. It looks like Roger may have already paid for it?

**How do I pay for ZenHub?**

Access your private Payments Dashboard here to manage your team’s ZenHub licenses. On the “Billing” tab, you can view and edit billing information (including credit card details), cancel subscriptions, and view billing history.

**How do admins work?**

Whoever makes the initial payment becomes that organization’s administrator. It’s helpful to grant administrative permissions to several members of your team, which can be done via the Dashboard’s “Users” tab. ZenHub’s Payment Dashboard has limited functionality for non-administrators.

**Comment by howarddierking** [comment]
ZenHub appears to be working fine. However, this issue is about Google analytics.

**Comment by henryyamamoto-concur** [comment]
Is Roger an admin in Google Search?

**Comment by rssanborn** [comment]
who setup/owns the acct with google? add me so I can get the billing sorted.

**Comment by henryyamamoto-concur** [comment]
@howarddierking Can you add Roger as an admin? roger.sanborn@concur.com  Thanks

**Comment by rssanborn** [comment]
site search billing updated, all good to go.
