### ISSUE TITLE
Clicking on Tools taking the user to aconnect utility page instead of tools page

### ISSUE THREAD

**Issue by patilanand** [concur/developer.concur.com#155]
**OS/Browser**
Mac/Chrome

**Repro**
Go to http://preview.developer.concur.com/
Click on Tools & Support -> Tools

**Actual**
It is taking user to aconnect Utility page instead of Tools page.

**Expected**
It should take the user to Tools page.

![snip20150824_20](https://cloud.githubusercontent.com/assets/5607025/9451868/16041fac-4a66-11e5-9416-192c57e3c91c.png)

**Comment by henryyamamoto-concur** [comment]
We don't have a landing page for tools as of yet as there are just two tools. We may get rid of this page soon so we'll keep it in the backlog to track.

**Comment by henryyamamoto-concur** [comment]
We need to determine if we even make these tools available. Likely we will remove these links.
