### ISSUE TITLE
aconnect Utility and Web Test Tool links are redudant on their own page

### ISSUE THREAD

**Issue by patilanand** [concur/developer.concur.com#157]
**OS/Browser**
Mac/Chrome

**Repro**
Go to http://preview.developer.concur.com/
Click on Tools & Support -> Tools
Click on Web Test Tool

**Actual**
On the top right hand section there are two hyper links Home / Web Test Tool. The Web Test Tool hyper link is redudant since the user is on the same page.

**Expected**
Remove Web Test Tool hyper link.

The same thing applies on aconnect Utility page too.

![snip20150824_19](https://cloud.githubusercontent.com/assets/5607025/9452205/dbf83fbc-4a67-11e5-9c57-ac25e1cb10b8.png)

**Comment by henryyamamoto-concur** [comment]
This is just a breadcrumb feature. We'll be tweaking it in the next fit and finish phase. Closing for now.

**Comment by patilanand** [comment]
@henryyamamoto-concur  I suggest you to keep this bug open and close this whenever you guys are doing the enhancement to breadcrumb feature.

**Comment by rssanborn** [comment]
@henryyamamoto-concur before we go live, let's discuss this page. acconnect is a tool that we cannot get away from due to TripLink partners. Webtest however should be retired in favor of much better, publicly known and supported (and multi-platform) tools such cURL, Postman, etc.
