### ISSUE TITLE
Concur logo on forums page link to forum page itself

### ISSUE THREAD

**Issue by patilanand** [concur/developer.concur.com#158]
**OS/Browser**
Mac/Chrome

**Repro**
Go to http://preview.developer.concur.com/
Click on Tools & Support -> Forum

**Actual**
The concur logo on forum page links to forum page itself. 

**Expected**
The concur logo should take the user to either concur site or developer portal.

**Comment by henryyamamoto-concur** [comment]
Changed the link to forum to open new window or tab.
