### ISSUE TITLE
Manage Apps - Go to Market -> Under Marketing your app, "View" links download files

### ISSUE THREAD

**Issue by yenemartin** [concur/developer.concur.com#165]
http://preview.developer.concur.com/manage-apps/go-to-market.html
Chrome /Mac

Scroll down to Marketing your app, and click on for example:App Center Partner Listing Form's View
I expect it to open the document in the browser for me to view.
Instead of opening the file for view on browser, clicking "View" downloads the files onto my computer.

**Comment by yenemartin** [comment]
The following links also start download:
App center Application Submission Form
Apps for Me Release Schedule

**Comment by henryyamamoto-concur** [comment]
The view works for PDF docs if you have a viewer installed. The Word doc will download regardless. I changed the wording on the Word doc to "download".
