### ISSUE TITLE
Privacy Policy and Terms Conditions hyperlink is not at the text place.

### ISSUE THREAD

**Issue by NelsonChang** [concur/developer.concur.com#166]
URL: http://preview.developer.concur.com/why-concur.html
OS/Browser: MacBook 15" & Chrome
Steps to reproduce the issue:(random)
1. Open the URL
2. move the mouse to Privacy Policy words.
Expected and Actual behavior
Actual:. It's un-clickable. the clickable area is above of the text.
Expect: the clickable area should be right at the text place.

PS. All the footer hyperlink are not at the text place.

**Comment by henryyamamoto-concur** [comment]
Could not repo this
