### ISSUE TITLE
Manage Apps - Go to Market -> Deal & Deployment Notification Form - opens old link

### ISSUE THREAD

**Issue by yenemartin** [concur/developer.concur.com#167]
Chrome/Mac
http://preview.developer.concur.com/manage-apps/go-to-market.html
Scroll down to Deploying Your App for Customers and click on 
Deal & Deployment Notification Form
Expected: redirected to preview -form
Actual: redirected to http://info.concur.com/forms/AppCenter-DealTracking

**Comment by henryyamamoto-concur** [comment]
This is actually the right site and is not on the old site.
