### ISSUE TITLE
Sandbox Configuration Assistance page doesn't show navigation control on left side

### ISSUE THREAD

**Issue by mattharrington001** [concur/developer.concur.com#169]
On: http://preview.developer.concur.com/tools-support/sandbox-configuration-assistance.html

The navigation control doesn't show up on the left side of the page.

All the other pages in the Tools section show that navigation control.

**Comment by henryyamamoto-concur** [comment]
We got rid of them for the forms. We plan on getting rid of the left-hand nav in this section.
