### ISSUE TITLE
Footers- "Edit this page in Github" and "Produced from .." should not be there

### ISSUE THREAD

**Issue by yenemartin** [concur/developer.concur.com#170]
On the footers these two links are active and forward  to our github source code. The links should not be there at all.

**Comment by howarddierking** [comment]
the links should _absolutely_ be there. What's your concern?

**Comment by yenemartin** [comment]
i thought this is customer facing page, does this mean it will allow customers to be able to edit the page?

**Comment by howarddierking** [comment]
yes - by design.
