### ISSUE TITLE
Support - Link on left bar of "Support" just goes to support (goes nowhere when on support)

### ISSUE THREAD

**Issue by WesWinn** [concur/developer.concur.com#174]
![screen shot 2015-08-25 at 2 00 36 pm](https://cloud.githubusercontent.com/assets/8117082/9479297/b256d662-4b31-11e5-8c0e-d2803bd96074.png)

http://preview.developer.concur.com/tools-support/support.html

**Comment by henryyamamoto-concur** [comment]
It's weird. I think it's how the folders are structuring the left-hand nav. I have another ticket open in next phase to get this fixed.
