### ISSUE TITLE
Update readme with instructions on updating docs directly

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#175]
A goal in open sourcing the docs repository is to give our developer community - both internal and external - the opportunity to have changes fixed more quickly by editing a problem document in the GitHub UI and "save" it, which will create a pull request. 

Can we please add some copy to the readme that outlines this?

**Comment by henryyamamoto-concur** [comment]
Fixed with commit 764f034c14d8c953e77037a3e169f81620b0d5e6
