### ISSUE TITLE
Support - Reference - HTTP Codes - Ensure concurconnecttech@concur.com is still being checked

### ISSUE THREAD

**Issue by WesWinn** [concur/developer.concur.com#179]
http://preview.developer.concur.com/tools-support/reference/http-codes.html

Note: If this email is dead, it shows up in many places and we may want to grep the address and update. I've emailed this address and await a reply. I'll try to see if anyone else knows its status as well.

**Comment by henryyamamoto-concur** [comment]
Still actively being used. Implementation will let us know if they want these email links removed in lieu of the support ticket system for current partners.

**Comment by rssanborn** [comment]
this page needs to die. we do not maintain a list of http codes and what they mean. We need to educate other teams where to locate this information. if it is absolutely required that we have a link, use http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by henryyamamoto-concur** [comment]
Opened new issue to track @rssanborn comment above: https://github.com/concur/developer.concur.com/issues/191
