### ISSUE TITLE
Sandbox creation just shows "request submitted"

### ISSUE THREAD

**Issue by WesWinn** [concur/developer.concur.com#186]
There's no key/secret posted like in old site, and for a user, it'd be unclear what a submitted request means and/or how to get a key/secret. See image below for what happens upon Sandbox creation submission:

![screen shot 2015-08-25 at 2 54 44 pm](https://cloud.githubusercontent.com/assets/8117082/9480724/8c9aa9be-4b39-11e5-97ba-457a96102a99.png)

**Comment by henryyamamoto-concur** [comment]
Closing. Now tracked in forms repo: concur/developer.concur.com-forms #14
