### ISSUE TITLE
Sandbox creation not creating Sandbox

### ISSUE THREAD

**Issue by WesWinn** [concur/developer.concur.com#187]
Fill out a sandbox creation form
Go to login after sandbox created
Can't login implies creation failed, or at the very least, user info isn't stored properly.

**Comment by henryyamamoto-concur** [comment]
This is a big one. This would be a blocker if you can't login to concur solutions after completing the form. 

Should work like current site: https://developer.concur.com/register

**Comment by henryyamamoto-concur** [comment]
There is a task in the original story about creating straw man port of existing backend. There may have been a misunderstanding that this also included sandbox creation, not just eloqua integration. https://jira.concur.com/jira/browse/WS-6926

**Comment by howarddierking** [comment]
no prob - would you mind porting that to the forms repo?

**Comment by henryyamamoto-concur** [comment]
Closing. Now tracked in forms repo: concur/developer.concur.com-forms #14
