### ISSUE TITLE
Slider on home page has copy centered - should not be

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#188]
I think this may be a result of fixing another issue on the other sliders that needed to be centered.

![screen shot 2015-08-25 at 3 39 21 pm](https://cloud.githubusercontent.com/assets/8781478/9481488/ab30107a-4b3f-11e5-93b3-527f163ed63b.png)

Should look like this:

<img width="885" alt="screen shot 2015-05-06 at 2 37 23 pm" src="https://cloud.githubusercontent.com/assets/8781478/9481490/b26db98c-4b3f-11e5-8f4a-dc3215ecf20b.png">

**Comment by nicklathe** [comment]
@henryyamamoto-concur  this is what it looks like on my screen. Currently looks like this on preview.developer.concur.com as well. It's responds to screen resize correctly as well.
![screen shot 2015-08-31 at 8 37 37 am](https://cloud.githubusercontent.com/assets/8847422/9582650/9088064e-4fbb-11e5-8fb0-294468522673.png)
