### ISSUE TITLE
Update site footer to show recent blog posts

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#194]
This was the issue tracking the recent blog post list in footer: https://jira.concur.com/jira/browse/COM-608

**Comment by merittrompeter** [comment]
So if we're linking to our own blog now, should we take out the plugin?

**Comment by henryyamamoto-concur** [comment]
Yup. If you overhead us.

**Comment by merittrompeter** [comment]
Great, thanks!

**Comment by howarddierking** [comment]
renamed to reflect current nature of the work

**Comment by henryyamamoto-concur** [comment]
Done with PR 364
