### ISSUE TITLE
Use correct Concur logo in the footer

### ISSUE THREAD

**Issue by cskelley** [concur/developer.concur.com#202]
Per the Concur Brand guidelines (http://www.concurbrand.com/toolkit-logo-type-color/#1410561576-1-23) the Concur horizontal logo should be used. Furthermore, the current logo is not compliant with guidelines:  "Note: The two elements of the logo, the c-dot pictogram and the CONCUR lettering, must always appear together. Exceptions exist for extremely tight-space usage in mobile apps."

**Comment by henryyamamoto-concur** [comment]
For our case, marketing didn't care that much, but they also said that because we have a responsive design with one target being mobile devices, they told us to go ahead and use that logo.

**Comment by cskelley** [comment]
:-) I still think we should fix it.
