### ISSUE TITLE
Create redirect pages for most frequently visited pages from old portal

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#250]
Need to create some redirect pages that automatically forward user to corresponding new page. Only for the top pages:

* developer.concur.com/register --> https://developer.concur.com/manage-apps/register.html
* developer.concur.com/docs-and-resources/documentation -->  https://developer.concur.com/api-reference/index.html
* developer.concur.com/docs-and-resources/support --> https://developer.concur.com/tools-support/support.html

**Comment by henryyamamoto-concur** [comment]
I'm looking for the lightest solution since this shouldn't be a long-term need. I know HTML redirects behave badly and are discouraged, what about JS redirects.

**Comment by howarddierking** [comment]
I've been thinking about this case along with a few others (e.g. `/` -> `/index.html`) and am curious whether it may make sense to spin a load balancer with a couple NGINX instances fronting the S3 bucket. Then we could more easily handle some of these issues that require a simple, but definite compute function. 

This could also enable us to offload a couple of these things from Akamai, is currently handling them by issuing redirects. 

@nicklathe, interested in your thoughts here...

**Comment by nicklathe** [comment]
I think NGINX could be a good way to handle it. We could do a 404 page through it, along with any other redirects we wanted, all with editing an easy conf file.

**Comment by howarddierking** [comment]
closing this issue as we'll be tracking further status in https://github.com/concur/developer.concur.com-gateway
