### ISSUE TITLE
samples are missing throughout the Dev Center

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#267]
The new Dev Center does not have example POST bodies like the old Dev Portal had.  E.g. the User API Resource (listed below) just lists the data elements and does not provide an example,  These examples not only help Partners see the formatting for Post content but it helps Support quickly reproduce Post examples and try them in our own sandboxes.

https://developer.concur.com/api-reference/user/company-notification-subscription-resource/user.html#createUser

**Comment by henryyamamoto-concur** [comment]
Currently being worked on as part of the Cadence project.

**Comment by henryyamamoto-concur** [comment]
We had some of this work done, but we'll need to find a new resource. I've found the value provided by Cadence does not justify the cost.
