### ISSUE TITLE
v2 Get Report Details needs to be more visible

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#268]
The v3 Entries API needs to be taken off the Developer Center due to bugs & missing supplemental APIs that it refers to but are not created yet.  Instead v2 GET Report Details needs to be located within the current page accessed by the "Entries" navigation side menu....

1. Replace this page: https://developer.concur.com/api-reference/expense/expense-report/expense-entry.html (which discusses v3 GET Entries) with this page:

https://developer.concur.com/api-reference-deprecated/version-two/expense-reports/expense-report-get.html

2. This line needs to be removed from the GET Report Details page:
"Find the newer version 3.0 here."

**Comment by henryyamamoto-concur** [comment]
Does this mean **all** of v3 Entries is no good? Or just the GET?

**Comment by dstaab** [comment]
Just the GET Entries so far.

Doug Staab
Manager, App Center Partner Enablement  | 425.590.5929 |  https://developer.concur.com/  |  www.concur.com/blog<http://www.concur.com/blog>
