### ISSUE TITLE
Dev Center is missing docs on v1 GET Reports List

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#276]
The GET Reports List (v1) results with a list of reports that have an encrypted report ID.  This report ID is necessary for the POST Report Workflow Action API since that API only recognizes the encrypted Report ID.  We don't have a v3 equivalent.

See: 
http://forum.developer.concur.com/t/cant-submit-api-v3-report/60/3

Can you locate the old GET Reports List v1 docs?

**Comment by henryyamamoto-concur** [comment]
I don't see a v1.0 GET Reports List. I found the fullreportdetails but it wasn't published on the old site and was hidden as deprecated. see attached
[Get Full Report Details - Deprecated | Developer Portal.pdf | uploaded via ZenHub](https://files.zenhub.io/563184753189efb459693d0b)

**Comment by henryyamamoto-concur** [comment]
I'm asking for access to an old archive from Sarra Lowe days. I'll look in there once I get access, but it's not in Pilar's folders.

**Comment by henryyamamoto-concur** [comment]
This is a really old issue that got burried. @dstaab Is this the missing doc referenced above? I still don't see a v1. This is v1.1: https://developer.concur.com/api-reference-deprecated/version-one-one/expense-report/get-list-of-reports.html  If so, it's not deprecated and I need to fix that.

**Comment by dstaab** [comment]
we can’t deprecate this yet as noted earlier
