### ISSUE TITLE
Receipt Documentation doesn't give full path for URL to Post receipt

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#278]
The documentation under "Create a New Receipt" has "Post /common/receipts"  The ParkWhiz dev emailed me because he used the instance URL of the token he received, and appended /common/receipts to it as the documentation states.  The resulting URL looked like this https://www.concursolutions.com/common/receipts  That URL gives a 404 Not Found error. 

The URL actually needs to be:  https://www.concursolutions.com/api/v3.0/common/receipts 

Our documentation should be updated to be "Post /api/v3.0/common/receipts"  so that devs can just append that to the instance URL we return with the token and make a successful call.

**Comment by henryyamamoto-concur** [comment]
This is true for ALL the URLs in 3.0 right?

**Comment by henryyamamoto-concur** [comment]
@elhansen748 Please verify on preview and I will push to livesite.

**Comment by elhansen748** [comment]
Good point, I think that is true.

**Comment by elhansen748** [comment]
Hey Henry, how to I view the preview site again?

**Comment by henryyamamoto-concur** [comment]
Just stick "preview." in front of the URL: preview.developer.concur.com

I didn't see any issues so I pushed it out to live as well. If something doesn't look right, I can fix it.

**Comment by elhansen748** [comment]
Thanks.  Sorry, the example I gave was for a US user.  We may want to change to /api/v3.0/common/receipts  because the user's instance URL might be eu1.concursolutions.com instead of www.concursolutions.com    Until the whole data center thing gets worked out, we probably shouldn't assume www

**Comment by henryyamamoto-concur** [comment]
OK. Will do. I was thinking about that halfway through.
