### ISSUE TITLE
Preview layout broken - Top font not right, Footer missing

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#288]
The preview branch layout isn't rendering correctly.
* Top font for "Developer Center" is wrong color
* Footer is missing (links, GitHub link, etc.)

Could be this [commit](https://github.com/concur/developer.concur.com/commit/e577995b3807ea4c95a672e5ad112fe14b81e9b9) that modified _layouts/default.html

**Comment by howarddierking** [comment]
yes - the CSS from the swagger UI stuff overrode top level styles - digging into that one today
