### ISSUE TITLE
Trip Resource missing data

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#290]
Noticed that the [Trip Resource page](https://developer.concur.com/api-reference/travel/itinerary/trip/trip-resource.html) is missing content:

* Get trip summaries (incomplete - stops at Response)
* Get trip details 
* Create new trip
* Update a trip
* Cancel a trip

Is there new/better documentation we can post? Otherwise, archived pages will need to be used to post missing content.

**Comment by drewdawson** [comment]
Please assign to @dmclaughlin-concur who owns the Itin API. The only APIs I own are the connection request APIs.

**Comment by dmclaughlin-concur** [comment]
Hi Henry,
There isn't any new documentation for these so I think we will need to retrieve from the archives.

Thanks,
Dan

**Comment by henryyamamoto-concur** [comment]
@dmclaughlin-concur Question for you. I've been spending a good portion of yesterday and today to recreate this, but is "Update a Trip" the attached?[POSTItineraryDetails.htm](https://files.zenhub.io/5644ed608294d8de6364c3e8)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by dmclaughlin-concur** [comment]
Hi Henry,
I think for that one, we would be ok to link to the existing POSTItineray details since it does include content on how to update a trip.  https://developer.concur.com/api-reference/travel/itinerary-tmc-thirdparty/index.html#postdetails

Thanks,
Dan

**Comment by henryyamamoto-concur** [comment]
OK, just made the commit so it should show up on preview in about 5 minutues

https://github.com/concur/developer.concur.com/commit/9cf658777ca4df3d4b4b6ec107ae683245fbd8de

Check it out here: https://preview.developer.concur.com/api-reference/travel/itinerary/trip/trip-resource.html

I did the heavy lifting, so feel free to edit.
