### ISSUE TITLE
Swagger Reference/API Explorer Fit and Finish

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#292]
The following is a list of minor tweaks and issues to resolve for the swagger reference/api explorer:

- [ ] Fix folder label and/or left-hand nav labels to "v3" and "v3.1"
- [ ] Fix [Entries GET](https://preview.developer.concur.com/api-explorer/v30/Entries.html) table width. So far as I can see, it's the only one requiring a side scroll.

**Comment by merittrompeter** [comment]
Re V Numbers:

Changing the folder names to include a ‘.’  breaks the menu. 
However, dashes aren’t a problem so we could change it to V3-0 and V3-1. 
Or we could do it with script, but that might not be ideal. Preferences?

Re Side Scrolling:

I’ve found several other tables with side scrolling. (e.g. PUT Expense, PUT Purchase Orders, POST Receipts, etc). We can pretty easily prevent it, but eventually, when the window gets small enough, it comes back. Just an FYI!

Cheers!

**Comment by henryyamamoto-concur** [comment]
I'm good with the hyphens. Now I have to worry about the static links to that section from the 3.0 documentation. For example, in some of the 3.0 pages I have links to these sections.

I noticed the side scrolling on some. As long as we can make the scrolling consistent across all the pages, I'm good. I notice it's only a few that start side scrolling when the page is wider.

**Comment by merittrompeter** [comment]
I'll see if I can compile a list of links so I can get those changes made asap.

**Comment by howarddierking** [comment]
wrt Swagger fit and finish in general, @jeffhandley was mentioning a visualizer other than swaggerui that looked promising. Jeff, so that we can have it for tracking, what was the name of that library again?

**Comment by jeffhandley** [comment]
It wasn't so much a visualizer, but more of a type system library that has a companion form-generation library that can generate forms from those types.  And the types can be created from JSON-Schema.

It's called tcomb and there's a group of related packages.

Just to name the salient few:

* https://www.npmjs.com/package/tcomb
* https://www.npmjs.com/package/tcomb-form
* https://www.npmjs.com/package/tcomb-json-schema

**Comment by nicklathe** [comment]
Those look cool. Wish there was a jekyll plugin version of that. Looks like there are only a couple options in the jekyll world.
