### ISSUE TITLE
GET Users v3.0 is missing from Dev Center

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#299]
v1.0 is the only version listed under the User resource.  We need info. about v3.0 since that allows a dev to get ALL users for a given client.

https://developer.concur.com/api-reference/user/company-notification-subscription-resource/user.html

**Comment by howarddierking** [comment]
is this the information currently found at https://developer.concur.com/api-explorer/v30/Users.html?

**Comment by rssanborn** [comment]
yes, that is the v3 User information. I believe the reference is to capture it as static docs as well like we have for all other v3 APIs.

**Comment by dstaab** [comment]
Roger is correct...we need static info.  A Dev is likely to read the current doc and not realize there is another version that allows them to get all users at once.
