### ISSUE TITLE
Sandbox not working on livesite and preview

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#301]
After completing the sandbox creation flow the following occurs:

* **livesite:** The form resets to blank state - looks like a login error
* **preview:** Goes to Concur login page with error that says login failed

**Comment by howarddierking** [comment]
@nicklathe are there ajax errors coming back from the forms handler?

**Comment by howarddierking** [comment]
there was a NAT that had shut down (one was still active though). I restarted it and get the same error - continuing to investigate.

**Comment by nicklathe** [comment]
I had a sandbox form error out with a CORS error, then I tried again and it went through.

**Comment by howarddierking** [comment]
Just now? if so, we really need to look at bumping the priority of changing the sandbox signup workflow to be async. The CTE service handling creation is just too unstable to use in a sync way.

**Comment by nicklathe** [comment]
Yeah, just now. I agree, it's super unstable. What would be next steps in changing sandbox signup workflow?

**Comment by howarddierking** [comment]
an async workflow in this case would consist of 2 high level changes.
1. putting the creation request into a queue and then trying (and retrying the creation) in the background
1. emailing (or similar) the user when the sandbox was successfully created.

It's this second item that will take a little more planning because it changes the expected user experience. The change is for the better IMO, but it will take some lead time from @henryyamamoto-concur

**Comment by henryyamamoto-concur** [comment]
Another report from the Japan team on sandbox error. I just tried and I just went back to the form in a blank state (https://developer.concur.com/manage-apps/register.html?result=failed#loginfailed).

Attached is what Tomohiro on the Japan team reported early this morning.
![error_after_clicking_submit_button](https://cloud.githubusercontent.com/assets/8781478/11569074/988dd1e2-99a4-11e5-82aa-c61d237c67ba.jpg)

**Comment by nicklathe** [comment]
Working on sending the errors from -forms to the UI. As a nice fix for the password length, I made a validation rule that the password must be at least 7 characters, as that is what the error we are getting states. So, we will fix this problem before a submit even happens now.

**Comment by TomoTsukui** [comment]
Thank you for your adding this issue to Sprint 12/7 - 12/18! Can you tell me when the release date of this Sprint is?

**Comment by henryyamamoto-concur** [comment]
@TomoTsukui We don't work with release dates. Once it's fixed and we merge the fix into the livesite it's available immediately.

That said, I've actually created three sandboxes tonight with no issues. A few things to keep in mind:
* Email used to create a sandbox cannot be an email used in any Concur product (past, current or future). It must be unique to the entire Concur system.
* Be sure you are logged out of any Concur product before starting the process
* Sandboxes may take more than a minute to create.

**Comment by howarddierking** [comment]
Also, just to be clear, this particular fix is scoped to providing high fidelity error messages coming from CTE. For the larger user experience discussion, I've created #309

**Comment by TomoTsukui** [comment]
Thanks, I've created one sandbox for the partner. 
By the way, when I select "Prospective Partner/Developer" in Relationship with Concur, this wizard fails.
