### ISSUE TITLE
update app cert form to be editable

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#306]
Hi Henry,
Attached is a Word doc.  Can you convert this to an editable PDF and replace the current non-editable PDF that is on the Dev Center now?

The current doc lives here:
https://developer.concur.com/manage-apps/app-certification.html
[Concur Application Submission Form v4a.docx](https://github.com/concur/developer.concur.com/files/55913/Concur.Application.Submission.Form.v4a.docx)

**Comment by henryyamamoto-concur** [comment]
Note that the doc is accessed from this page as well: https://developer.concur.com/manage-apps/go-to-market.html

I don't have a way to make the PDF editable. I can post the Word doc, but need to make the buttons markable. Otherwise, they'll need to print and put check marks in on paper.

**Comment by dstaab** [comment]
Erik – wasn’t the app cert form an editable pdf?

**Comment by dstaab** [comment]
Disregard…just saw the other emails. Thanks Henry

From: Staab, Douglas
Sent: Tuesday, December 08, 2015 1:06 PM
To: 'concur/developer.concur.com'; concur/developer.concur.com
Cc: Hansen, Erik
Subject: RE: [developer.concur.com] update app cert form to be editable (#306)

Erik – wasn’t the app cert form an editable pdf?

**Comment by henryyamamoto-concur** [comment]
The form is actually editable. It's not editable in a browser (may depend on type you're using). User will need to download and open in an editor tool of their choice.
