### ISSUE TITLE
Change sandbox creation workflow to be async

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#309]
The current sandbox workflow is linear as follows:
- request from form to our backend (waits)
- our backend calls CTE to provision a sandbox (waits)
- response flows all the way from CTE through our backend to the form

There are 2 main problems with this approach
- CTE can take up to a minute to respond
- CTE is periodically unavailable (this could be due to expected and unexpected outages)

The result is either a slow or broken user experience - neither are acceptable. 

Going forward, we need to make the user experience for creating a sandbox async. The flow should then be as follows:
- request from form to our backend
- immediate response from backend saying that the form was received
- backend sends request to CTE to provision sandbox and retries as necessary
- on success, our backend notifies the user (via email?) that sandbox is ready

**Comment by bhague1281** [comment]
Sandbox creation is in the process of being deprecated.
