### ISSUE TITLE
Updatepps for Me Release Schedule in the partner resources page

### ISSUE THREAD

**Issue by serafinj** [concur/developer.concur.com#314]
Please update our Apps for Me Release Schedule in the partner resources page.

Current file:https://developer.concur.com/manage-apps/go-market-docs/apps_for_me_release_schedule.pdf

UPDATED file: https://concur.box.com/s/sel9imho429rpdmdlhcybzq6k1axe2se

**Comment by henryyamamoto-concur** [comment]
https://github.com/concur/developer.concur.com/commit/52e13ebb7e35bb53ead3730957a88afcc19ba851

I updated this per the email from yesterday. It's currently in preview.developer.com. Pushing out today to the livesite.

Let me know if you've updated the doc since yesterday morning.
