### ISSUE TITLE
Need to track downloads on "Go To Market Page"

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#322]
We need to track clicks on the download links on this page: https://developer.concur.com/manage-apps/go-to-market.html

Found this info on GA regarding download link tracking, but not sure how we've implemented GA on developer.concur.com: https://support.google.com/analytics/answer/1012044?hl=en

**Comment by henryyamamoto-concur** [comment]
Apparently, the clicks aren't showing up in GA. Can we run some tests to confirm either way?

**Comment by merittrompeter** [comment]
Oh no! Maybe I misunderstood how we wanted to track. I'm seeing the Go-To-Market clicks under 'Behavior' then 'Events on my GA dashboard.

**Comment by merittrompeter** [comment]
[Analytics All Web Site Data Top Events 20160111-20160210.pdf](https://files.zenhub.io/56bd009295307a0978e7b44d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by henryyamamoto-concur** [comment]
Just got feedback that it looks good now that they know where to look for the data. Re-closing.
