### ISSUE TITLE
Creating an Expense Report details

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#327]
There isn't enough information on how to create a report via the POST API.

see:  https://developer.concur.com/api-reference/expense/expense-report/reports.html#post

How does a Dev know what the post body is supposed to be (e.g. required fields, format of data, etc.)

Will this have Swagger?

**Comment by howarddierking** [comment]
it certainly can have Swagger - in fact, this would be a great way to improve API documentation going forward rather than having so much of it be ad-hoc

**Comment by henryyamamoto-concur** [comment]
We will be merging content from the integrate site as well as going with a more intuitive design in our next phase.
