### ISSUE TITLE
Update LOA on Partner Resources Page

### ISSUE THREAD

**Issue by serafinj** [concur/developer.concur.com#330]
I just got an updated Letter of Authorization from legal with a version included. Can you please update the resource page?

Updated doc:
https://concur.box.com/s/m48naypqntulqifjbwsp3bfu9ng2vrzr

Thanks!

**Comment by henryyamamoto-concur** [comment]
The link above didn't work, but I found the folder with all the docs. I used this one: https://concur.box.com/s/m48naypqntulqifjbwsp3bfu9ng2vrzr

**Comment by serafinj** [comment]
Thanks!
