### ISSUE TITLE
Add edge caching for livesite

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#347]
Currently all requests are flowing to origin. This is because we wanted to have quick turn around in the early days of the site. However, now that the site has been around for a while, we should turn on edge caching to improve last mile performance as well as take some load off of the origin.

**Comment by charlieconcur** [comment]
@howarddierking Are we actually going to do this given it's been well over a year since the issue was opened?

**Comment by howarddierking** [comment]
Actually, yea, I think we should probably do this one for more reasons than just edge caching (though with the benefit of time, I think we should do it differently than how I was thinking at the time).

By introducing CloudFront into the topology, we should be able to have this one service handle edge caching, SSL termination, and routing rules. This will enable us to get rid of the existing ELB + NGINX cluster and make dev center even simpler / more hands off from an operational perspective.

**Comment by charlieconcur** [comment]
Does it change the conversation much if we move documentation to GitHub Pages?

I've recently learned with each change in documentation we also build and deploy the app management pieces (even if they didn't change) so if we keep them all together, maybe not so much?

**Comment by howarddierking** [comment]
GH Pages isn't an option. I'll explain what is I think a lot of missing context offline

**Comment by charlieconcur** [comment]
Moved to https://jira.concur.com/browse/DVCNTR-10
