### ISSUE TITLE
create editorial timeline for developer blog

### ISSUE THREAD

**Issue by merittrompeter** [concur/developer.concur.com#348]
- create an editorial schedule for blog posts on new developer blog
- include other teams in authorship rota

**Comment by henryyamamoto-concur** [comment]
Great! In addition to regular, authored blog posts, we'll also post the following:
* Release notes summary with links to full docs
* Status of APIs if there is an issue
* Intro of new services, tools and APIs

I'll also reach out to our business team so we can do introductions of new apps so we can show the dev community what other folks are doing on our platform

**Comment by henryyamamoto-concur** [comment]
I have the pipeline going for now and assigning via that route.
