### ISSUE TITLE
Add privacy policy request field to Application Submission Form

### ISSUE THREAD

**Issue by cskelley** [concur/developer.concur.com#354]
Per Legal (Mark Voigts), please change the Application Submission Form to include a section that asks for the partner's privacy policy URL as it applies to the application being certified ... and a suitable place for them to provide that URL. Legal has approved this language:

Provide the URL to your privacy policy that applies to this application:

**Comment by henryyamamoto-concur** [comment]
I'm going to forward this request to Doug's team as they own this doc. We can post the updated doc once they update.
