### ISSUE TITLE
new App Cert Submit form

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#356]
Henry,

Legal asked to have the app cert form updated so that we ask for a hyperlink to the Partner's privacy policy.

I also added some questions that correspond to Jacqueline's SF fields.

Please post as soon as you can.  thanks.
[Concur Application Submission Form v4_1-28-16.docx](https://github.com/concur/developer.concur.com/files/110654/Concur.Application.Submission.Form.v4_1-28-16.docx)

**Comment by henryyamamoto-concur** [comment]
Did this earlier today.
