### ISSUE TITLE
Post sample blog posts (actually real, but so we can deploy faster we use these).

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#358]
* Blog on Amazon Echo integration: https://blog.concurlabs.com/index.php/2015/11/19/amazon-echo-can-i-build-an-app-for-concur/
* Blog introducing Concur Labs: https://www.concur.com/blog/en-us/whats-brewing-in-the-lab-concur-labs

**Comment by merittrompeter** [comment]
Some of the links on the two original posts are currently not working. Should I leave them out?

**Comment by henryyamamoto-concur** [comment]
Yeah, leave them out. Thanks.
