### ISSUE TITLE
Can't expand API menu on mobile device

### ISSUE THREAD

**Issue by cskelley** [concur/developer.concur.com#387]
When accessing https://developer.concur.com from a mobile device, the API menu doesn't expand to list the API Reference/API Explorer/API Guides options. The Manage Apps and Tools & Support menus do expand, however. I experienced this on an iPhone 6s using both Safari and Chrome.

**Comment by henryyamamoto-concur** [comment]
Looks like when we added the additional drop downs, we may have missed some accompanying code. @merittrompeter If you have time in this sprint, can you take a look at this one?

**Comment by merittrompeter** [comment]
Absolutely, will look at that right away.
