### ISSUE TITLE
Check GA link tracking

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#391]
On [Go to market page](https://developer.concur.com/manage-apps/go-to-market.html) check to verify if this link is being tracked in GA:
http://info.concur.com/forms/AppCenter-DealTracking

**Comment by merittrompeter** [comment]
It is! [Analytics All Web Site Data Top Events 20160119-20160218.pdf](https://files.zenhub.io/56c7574b16c1bcfd62940f5e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by henryyamamoto-concur** [comment]
Turns out that one is not a PDF. That may be why they were having trouble finding it. We may want a different font/icon for that later. It's being tracked so we can close this one. There's another issue for changing the labels to paths to make it easier for the marketing team to find and track.
