### ISSUE TITLE
Update Marketing Section of Partner Resources Page

### ISSUE THREAD

**Issue by serafinj** [concur/developer.concur.com#409]
We've now consolidated a few of the marketing guideline docs and need to update the partner resource page to reflect the changes. 

Can you remove the following docs:
Concur Brand Guidelines
App Center Badge Use Guidelines
App Center PR Toolkit

Replace with:
App Center Marketing Toolkit (attached)
[2016_02_02_Concur-partner-toolkit_R5.pdf](https://github.com/concur/developer.concur.com/files/150550/2016_02_02_Concur-partner-toolkit_R5.pdf)

I'm assuming we'll need to create a new URL here and new reporting for this? Let me know what you think would be the best way to manage that?

Also, if there is any way to get this up this week (before we head to Fusion) that would be super helpful!

Thanks!

**Comment by henryyamamoto-concur** [comment]
Will get this in the sprint that starts today and talk about it at our planning today.
@serafinj Can you provide replacement copy for this section?

**Comment by henryyamamoto-concur** [comment]
* Remove sections noted above
* Add new App Center Marketing Toolkit.

**Comment by serafinj** [comment]
Thanks Henry. Here is the updated copy for this section:

Marketing Your App
As you prepare to launch your app, please review the App Center Marketing Toolkit which will help you complete your App Center Listing Form for submission. App Center guidelines along with best practices and templates are included; please also reference for future marketing activities or listing updates.

App Center Marketing Toolkit: Included in the toolkit are guidelines for: product naming, Concur logo/brand use, App Center badge use, PR, social media, search and more. Please reference carefully as you prepare your App Center Listing Form.

App Center Listing Form: Your listing will serve as the primary location where companies and users will learn more about your app, leading to inquiries or end user connections. Please reference the App Center Marketing Toolkit as you complete the form and submit for review to include your app in the App Center.



Jacqueline
