### ISSUE TITLE
Inventory of all third-party components used for Dev Center

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#516]
Due to the scheduled creation of a new data center for China, we need to provide a list of all third party components used for dev center. This should include any OS components and/or libraries.

Starting here:
* GitHub
* CircleCI
* Jekyll
*  Bootstrap
* Marketo
* Google Analytics
* Vagrant
* Disqus
* Discourse
* Docker
* Unify (bootstrap template)

**Comment by henryyamamoto-concur** [comment]
Anything other to add to this list? @nicklathe @merittrompeter

**Comment by nicklathe** [comment]
If we want an exhaustive list:
* Akamai
* AWS
* NGINX
* Quay
* myGet
* a number of open source npm modules

**Comment by nicklathe** [comment]
Also,
* a number of open source Jekyll pluggins
