### ISSUE TITLE
Add print function to Terms of Use

### ISSUE THREAD

**Issue by cskelley** [concur/developer.concur.com#529]
https://developer.concur.com/Terms-of-Use.html

When I'm negotiation with prospective new Platform partners, they often want a copy of the API License and Services Agreement (our agreements refer to this URL). It would be nice if there were a print function on this page so the partner could print out the API License and Services Agreement without all the other text that appears on the page.

**Comment by henryyamamoto-concur** [comment]
Add a print button that only prints the terms content and not the navigation and other extraneous elements.
