### ISSUE TITLE
Make "Privacy Policy" a clickable link

### ISSUE THREAD

**Issue by cskelley** [concur/developer.concur.com#531]
https://developer.concur.com/manage-apps/register.html

At the end of the sandbox registration form, there's a checkbox with the text "I Agree to the Terms of Use and Privacy Policy". Terms of Use is a hyperlink but Privacy Policy is not. Can/should the Privacy Policy be a hyperlink, too?

**Comment by henryyamamoto-concur** [comment]
Please add hyperlink for Privacy Policy: https://www.concur.com/en-us/privacy-policy

**Comment by henryyamamoto-concur** [comment]
Issue moved to [concur/developer.concur.com-forms #74](https://github.com/concur/developer.concur.com-forms/issues/74) via [**ZenHub.io**](https://www.zenhub.io/)
