### ISSUE TITLE
API Guide Navigation

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#532]
This case involves the API Guides page.  There is a main menu called, "Expense".
There are 3 sub topics displayed within the Expense main menu that need to be organized within their own sub menu called, "Adding Users".  For example, the outline navigation should be:

Expense
_Adding Users
__Create  A User
__How To Identify Group Codes for Standard Edition Clients
__How To Provision A Basic User Record Into Concur 

see existing page at:
https://developer.concur.com/api-guides/index.html

**Comment by henryyamamoto-concur** [comment]
Is there a way to add a sub-nav under Expense so "Adding Users" is the one item and under that is contained the three docs there now?

**Comment by bhague1281** [comment]
Currently, there isn't, and adding an additional subnav would involve some major refactoring of the current navigation. Instead of deepening the hierarchy, how about prepending each doc with "Adding Users", similar to the docs under "Travel"?

**Comment by henryyamamoto-concur** [comment]
We will be reorganizing content in our next big initiative including a redesign so we'll close this. It's not worth the level of effort to enable this on the current site.
