### ISSUE TITLE
Incorrect page link in the API Guides section

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#533]
The "How To Identify Group Codes for Standard Edition Clients" sub menu in the left navigation menu on the API Guides page actually links to the "How To Provision A Basic User Record Into Concur" page.

Please correct the link to the page called, "How To Identify Group Codes for Standard Edition Clients"

Here is the page in question....
https://developer.concur.com/api-guides/expense/how-to-identify-group-codes-for-standard-edition-clients.html

**Comment by henryyamamoto-concur** [comment]
Superseded.
