### ISSUE TITLE
Fix images on ereceipts guide page

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#544]
I tried. I give up. Need professional help.

The images on this page are not showing up: https://preview.developer.concur.com/api-guides/e-receipts.html

**Comment by henryyamamoto-concur** [comment]
BTW, I tried it with regular HTML IMG tags and it didn't work so I tried the crazy markdown ones that are there now.

**Comment by howarddierking** [comment]
either 

* put a dot in front of the slash (e.g. `./images/...`) 
* take away the root slash (e.g. `images/...`)

**Comment by henryyamamoto-concur** [comment]
Fixed. Thanks.
