### ISSUE TITLE
SPIKE: Figure out a way to have specific pages in Dev Center be no index (both internal & external search)

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#546]
Requirements:
* Pages must be "no index" to external search engines and internal search

Determine if we can do this and how we'd do it.

**Comment by henryyamamoto-concur** [comment]
@howarddierking FYI. I modified an existing issue to be the tracker for the no index via front matter.

**Comment by merittrompeter** [comment]
Just had a quick look a this, looks like the way to do this is setting a boolean in your front matter then injecting a meta tag in the template based on the truth of that value. 

http://jamiecollinson.com/blog/how-to-noindex-pages-with-jekyll

**Comment by howarddierking** [comment]
@merittrompeter - yup. This is the same pattern that I implemented for having search ignore the preview branch (https://github.com/concur/developer.concur.com/blob/preview/_layouts/default.html#L16). You can probably just add a check to that same conditional for an additional front matter variable.

**Comment by henryyamamoto-concur** [comment]
The markdown files in this folder should be all "no index":
https://github.com/concur/developer.concur.com/tree/preview/api-alpha

**Comment by henryyamamoto-concur** [comment]
Using preview function and it seems to be working with no issues.
