### ISSUE TITLE
CSS fix for hashes without a space not rendering headers correctly

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#554]
There was a change somewhere along the way that invalidated headers rendering if there is no space after the hash and text. (see example: https://developer.concur.com/api-reference/callouts/fetch-attendee.html)

If there is a space, it's rendering correctly.

Is there a way to fix this in CSS vs. going into each file and adding a space after the hashes?

**Comment by merittrompeter** [comment]
I think it's the space between the has and text that invalidates it. 
#Example will not render properly on any editor, but # Example will.

I've gone through and changed all the places I could spot it. PR#555.
