### ISSUE TITLE
descriptions are wrong in model on Swagger

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#562]
Henry,
I received an error when trying to edit the Swagger page directly, indicating I don't have write access to that project.  So, I'm submitting this manually...

The image below is from this page in Swagger.  You have to click on the "Model" tab, not the Model Schema:

https://developer.concur.com/api-explorer/v3-0/DigitalTaxInvoices.html

All of the descriptions are repeated in error describing the Status for every data element.

![image](https://cloud.githubusercontent.com/assets/15145162/15714006/b41f8aba-27cd-11e6-9f78-be128ecd1569.png)

**Comment by henryyamamoto-concur** [comment]
Needs another new export of the JSON so we can correct these instances throughout swagger.

**Comment by dstaab** [comment]
ok, is this a call to action for me or someone else?

**Comment by henryyamamoto-concur** [comment]
@dstaab  For dev team.

**Comment by henryyamamoto-concur** [comment]
Fixed. Currently in preview will merge to livesite when all checks out
