### ISSUE TITLE
JWT validation for Swagger implementation

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#607]

**Comment by howarddierking** [comment]
Please describe what you want.

**Comment by henryyamamoto-concur** [comment]
Circling  back on this. The current API Explorer's token functionality keys off of the Auth that will be deprecated once new Auth is available. We need to ensure this function still works in the world of new Auth.

**Comment by drewdawson** [comment]
Thanks for working on this. I think this is a key deliverable of calling the new Auth service complete as Swagger is heavily used by our suppliers @rssanborn FYI

**Comment by howarddierking** [comment]
@henryyamamoto-concur and I talked about this in more detail and don't believe that there should be a problem with the Swagger handling itself. We do need though to make sure that we're putting the correct token scheme in the request when it is sent from the browser in the `authorization` header. At present, I believe that this value is `OAuth` where for the new tokens, it should be `Bearer`.

**Comment by henryyamamoto-concur** [comment]
Can we assign this to someone so it doesn't break when new OAuth goes live and old gets shut down?

**Comment by howarddierking** [comment]
We can assign it once Brian starts

**Comment by drewdawson** [comment]
When is that date? Would completion meet the October release deadline?

**Comment by henryyamamoto-concur** [comment]
This has to be a high priority to check to make sure it won't break. Can we make sure Brian has enough support to have this completed by Oct. 14?

**Comment by howarddierking** [comment]
proposed fix merged in with commit 02f61916e19c802dec4e4e69d8c1360f73ba15f5. @drewdawson, can you verify and confirm on preview.developer.concur.com?

**Comment by mantralavinay** [comment]
Thanks @howarddierking, we will test this as part of our story where we are rolling out the updated swagger to use the new JWT.

**Comment by henryyamamoto-concur** [comment]
Fixed.
