### ISSUE TITLE
Receipts API documentation needs to list out Scopes

### ISSUE THREAD

**Issue by lokeuei** [concur/developer.concur.com#646]
Receipts v4 API doc need to list down scopes that the service honors along with the description of the scope. Here are the guidelines to naming scopes and the necessary data required:

https://github.concur.com/core/app-mgmt/wiki/Best-Practices:-Application-Scopes

**Comment by pranali-concur** [comment]
Required scopes section - https://github.com/concur/receipt-service/blob/docs/doc/external/receipt-go-live-documentation.md#RequiredScopes - lists receipts.write, receipts.read and receipts.writeonly and a description.
