### ISSUE TITLE
Akamai Integration

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#67]
- [x] Setup CDN with Akamai
- [x] Flush CDN as a part of build process for Akamai
- [x] Terminate SSL at network edge
- [ ] Setup DNS (notify 7 days prior to launch)

**Comment by howarddierking** [comment]
currently waiting for Akamai to deploy edge cert - should happen this week

**Comment by howarddierking** [comment]
Akamai is setup - just need to change Concur DNS to point to it

**Comment by howarddierking** [comment]
DNS remapped for preview - will open a different ticket for the final DNS cname
