### ISSUE TITLE
Change sandbox to only create US entity

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#671]
Expense team refactored part of the company create process to focus on single country deployments. This change should improve performance of sandbox creation as well.

Change 'ActiveCountries' to 'US' only

**Comment by henryyamamoto-concur** [comment]
Still awaiting feedback from expense team on status.

Status:
* Tested locally, but noticed that making this change slowed the process down rather than make it faster.

**Comment by bhague1281** [comment]
Merged into the forms handler (PR 78)
