### ISSUE TITLE
Add Google Analytics to Discourse (Concur Dev Forums)

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#676]
Just noticed that we don't include forum traffic in our Google Analytics reporting. I'm thinking we should keep for Forum traffic as a separate GA account so simplify reporting? It's not a requirement but would like info on how best to implement with the following requirements:

- Add ability to track: 
  - User visits
  - New users
  - Views by topic
 

Here's where you'd setup GA in Discourse: https://forum.developer.concur.com/admin/site_settings/category/basic

**Comment by bhague1281** [comment]
Added GA reporting for Discourse as a separate property. I also created a dashboard that displays those three metrics. It should be under Dashboards > Shared > Metrics
