### ISSUE TITLE
Decommission locally managed NAT in favor of AWS Managed NAT 

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#694]
https://aws.amazon.com/about-aws/whats-new/2015/12/introducing-amazon-vpc-nat-gateway-a-managed-nat-service/

**Comment by howarddierking** [comment]
Here's what I think the steps are, but you'll probably want to verify.

1. create 3 NAT Gateways, one for each public subnet; assign a new EIP to each
1. create a new route table `Private-C` so that we’re no longer doubling up on 2 subnets sharing a NAT
1. for each route table, update the 0.0.0.0/0 entry to point to the nat by ARN
1. housekeeping - delete the old EIPs and then tear down the NAT CloudFormation stack

**Comment by bhague1281** [comment]
AWS-managed NAT gateways have been set up, and old instances have been destroyed.
