### ISSUE TITLE
Redirect old URL to new URL

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#698]
@bhague1281 I believe @howarddierking was using NGNIX to redirect old URLs so you may want to check with him to keep the redirects consistent and trackable in one place. Thanks.

Redirect the old link (https://preview.developer.concur.com/api-preview/receipts/apidoc.html) to the new link (https://developer.concur.com/api-preview/receipts/1_getstarted.html)

**Comment by bhague1281** [comment]
Gateway has been reconfigured with the redirect.
