### ISSUE TITLE
Create App Form

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#725]
Provide the ability to complete a form that spins up the "create app" process from the dev center.
- Must have form with all required fields
- Must label all fields with required information
- Must provide an error messages, for incomplete required fields and show which ones are incomplete
- Must provide an error message for exceeding max characters for any field with limits
- Must have a way to "cancel"
- Must have a way to "submit"
- Must set app to "disabled" by default when app is created (user can enable in edit mode once app is created)
- Must provide an error message if app creation is not successful with info on how to recover or what to do next.
- Must go to App Details page view after successful completion of app creation process. This is where the user is dropped after form is submitted and app created.

**All Fields are Required**:
- "Name of App" (100 characters max)
- "Description" (5000 characters max)
- "Application Type" (select one): Business, Consumer
- "Select Allowed Grants for this App" (multiple allowed): Authorization Code, Implicit, Refresh Token, Client Credentials, Password, OTP
- "Select Scopes Allowed for this App" (multiple allowed):  https://github.concur.com/core/app-mgmt/wiki/List-of-Scopes  We'll need to determine an elegant and useful way to display these. It may require a pop-up over the form or something similar. I want to avoid cluttering the form.
- "List Redirect URLs for this App": (checking with Loke on whether this is just one field and URLs are separated with commas or something else)

**For Reference Only**:

{
            "name": "id",
            "type": "string",
            "multiValued": false,
            "description": "Unique identifier for the Application - a uuid4 value.",
            "required": false,
            "caseExact": false,
            "mutability": "readOnly",
            "returned": "default",
            "uniqueness": "server"
        },
        {
            "name" : "name",
            "type": "string",
            "multiValued": false,
            "description": "Display name of the application (<100 chars)",
            "required": true,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "server"  
        },
        {
            "name" : "description",
            "type": "string",
            "multiValued": false,
            "description": "Human readable description of the application (<5000 chars)",
            "required": false,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "server"  
        },
        {
            "name" : "owner",
            "type": "string",
            "multiValued": false,
            "description": "principal that owns this app. a UUID4 value. Obtained from the current user who's creating the app.",
            "required": false,
            "caseExact": false,
            "mutability": "readOnly",
            "returned": "default",
            "uniqueness": "server"
        },
        {
            "name": "allowedGrants",
            "type": "string",
            "multiValued": true,
            "canonicalValues": [
                "authorization_code",
                "implicit",
                "refresh_token",
                "client_credentials",
                "password",
                "otp"
                ],
            "description": "list of grants allowed for this app, pick list",
            "required": true,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "none"
        },
        {
            "name": "appType",
            "type": "string",
            "multiValued": true,
            "canonicalValues": [
                "Business",
                "Consumer"
                ],
            "description": "list of application types - Pick list",
            "required": true,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "none"
        },
        {
            "name" : "certified",
            "type": "boolean",
            "multiValued": false,
            "description": "is this app certified? - For display only",
            "required": false,
            "caseExact": false,
            "mutability": "readOnly",
            "returned": "default",
            "uniqueness": "server"
        },
        {
            "name" : "enabled",
            "type": "boolean",
            "multiValued": false,
            "description": "is this app enabled? - Switch",
            "required": false,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "server"
        },
        {
            "name": "allowedScopes",
            "type": "string",
            "multiValued": true,
            "description": "list of scopes allowed for this app - multi-select picklist https://github.concur.com/core/app-mgmt/wiki/List-of-Scopes",
            "required": true,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "none"
        },
        {
            "name": "redirectUris",
            "type": "string",
            "multiValued": true,
            "description": "list of redirect_uris allowed for this app",
            "required": true,
            "caseExact": false,
            "mutability": "readWrite",
            "returned": "default",
            "uniqueness": "none"
        },

**Comment by henryyamamoto-concur** [comment]
@lokeuei Can you review the requirements and fields to make sure this captures the requirements?

And specifically for the redirect URLs, it's just one field correct?

**Comment by lokeuei** [comment]
Sorry! totally didn't see this.

1. Redirect URLs should be an array. They can create more than 1 redirect URLs. I think we can keep the cap at 50. 
2. Authorization Grants: we should provide links to our auth documentation to describe what those grants are.

**Comment by bhague1281** [comment]
Development for application mutations in Orchestration has been completed. Waiting on code review and testing.

Additional to-do items:

- [ ] New applications should add `refresh token` as a default grant
- [ ] New applications should add `openid` as a default scope
- [ ] Incorporate GraphQL calls into the form using [Apollo](http://dev.apollodata.com/)
