### ISSUE TITLE
App Details Page

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#727]
The App Details Page will display information about a specific app. It is a view only page with the option to EDIT the app.
- Must display the following:
  - Name of App
  - Description of App
  - Allowed Grants (show each grant allowed for this app)
  - App Type
  - Certified (Y/N status)
  - Enabled (Y/N status)
  - Allowed Scopes (show each scope allowed for this app)
  - Redirect URLs (show each redirect URL for this app)
  - App Secret (method to hide/show - default hidden)
    -Must provide button or method to edit the modifiable fields.

**Assumptions:**
- Some other service will set the status of wether the app is certified or not

**Comment by henryyamamoto-concur** [comment]
@lokeuei Can you review the requirements to make sure this captures the requirements?

**Comment by bhague1281** [comment]
- [ ] UI for displaying information
- [ ] App endpoint in orchestration
- [ ] App secret management

**Comment by bhague1281** [comment]
App secret will only be able to be regenerated... not shown.
