### ISSUE TITLE
Edit App Page

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#728]
The "Edit App" page is essentially the same as the "Create App Form" with the following differences:
- Must have fields that are populated with the last entered strings/variables
- Must have a button to obtain a new secret "Get New Secret"
  - Must display a warning prior to obtaining and replacing the app secret: "Are you sure? Y/N"
- Must have a method to cancel edits and return to "App Details" page.
- Must have a method to save changes and return to "App Details" page.

**Comment by bhague1281** [comment]
(no edit button for now)
