### ISSUE TITLE
broken link for March 2016 release notes

### ISSUE THREAD

**Issue by mattharrington001** [concur/developer.concur.com#735]
REPRO:
1. go to https://developer.concur.com/tools-support/release-notes
2. open link for March 2016 Developer Platform Release Notes: https://developer.concur.com/blog/2016/03/15/march-release-notes.html

RESULT:
404

From the context of the similar links on this page, I can't tell what the correct url is for this. Or should the link just be removed?

This appears to have started breaking Sept. 23.

**Comment by mattharrington001** [comment]
@henryyamamoto-concur Can you check this out? (I don't have perms to assign bugs in this repo.)

**Comment by mattharrington001** [comment]
@henryyamamoto-concur Can you check this out? (I don't have perms to assign bugs in this repo.)

**Comment by henryyamamoto-concur** [comment]
Weird since it's a public repo. Just fixed it
