### ISSUE TITLE
Add a UI element pointing people to the GitHub repo

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#75]
Because we're making the source of the Web site publicly accessible, we need to make sure that folks know how to get to the site and make changes - something like a "fork me on GitHub" earmark - though probably different since this is a content site.

**Comment by nicklathe** [comment]
How about something like this? This is what I did at Microsoft. ![screen shot 2015-08-20 at 1 29 22 pm](https://cloud.githubusercontent.com/assets/8847422/9394834/82b070d0-473f-11e5-8190-902685c71e92.png)
