### ISSUE TITLE
Check Blog posting instructions on wiki and add changelong posting instructions

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#754]

**Comment by henryyamamoto-concur** [comment]
Or @bhague1281 can take this one

**Comment by bhague1281** [comment]
Updated instructions

https://github.com/concur/developer.concur.com/wiki/Creating-a-Blog-post
https://github.com/concur/developer.concur.com/wiki/Creating-a-Change-Log-post
