### ISSUE TITLE
Clean up changelog list display for better readability

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#756]
We can discuss before changes are implemented, but here are the issues to resolve:
* Provide more padding or some other element to better distinguish one post for another
* Reduce pt size of fonts for the titles

https://preview.developer.concur.com/changelog/

**Comment by henryyamamoto-concur** [comment]
One idea is to break up the posts by Month/Year so we can both break up the posts and make it easier to find by month.

**Comment by bhague1281** [comment]
Broke up posts by adding horizontal rules (similar to the blog), as well as removed excerpts.
