### ISSUE TITLE
Ordering fix

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#759]
For the new "Receipts" section in API-Reference, can we change the order of the items in that section to display:

Get Started
Supported Receipt Types
Sample Receipts
Response Codes

For the new "Authentication" section in API-Reference, can we change the order of the items in that section to display:

Getting Started
Authentication

**Comment by bhague1281** [comment]
This would require renaming the files, which can be held off as discussed.

**Comment by bhague1281** [comment]
This can now be done ( #843 )
