### ISSUE TITLE
markdown is a mess on REST API Basics page

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#76]
http://preview.developer.concur.com/docs/guides/REST-API-Basics.html

Many problems with the markup here

**Comment by charlieconcur** [comment]
Revised markup which may fix several of the issues can be found here: https://github.com/concur/receipt-service/wiki/REST-API-Basics

**Comment by henryyamamoto-concur** [comment]
The same issue appears to be impacting this page as well: 
http://preview.developer.concur.com/docs/guides/index.html

I've checked the markdown and it has the right ``` marks in the right places, but for some reason it's not rendering properly on the site. I've even tried cutting and pasting the code from Charlie's receipt page and no bueno.

Is the CSS being applied based on the front matter "style: reference" or is it only applying it to the api-reference folder?

**Comment by nicklathe** [comment]
After a little research, it looks like Jekyll prefers ~~~ for code blocks instead of ```.

**Comment by charlieconcur** [comment]
Well...the problem with the statement about Jekyll:

* The markdown for http://preview.developer.concur.com/docs/guides/REST-API-Basics.html doesn't use any ``` -- It only uses tabs.
* ~~~ is not a part of the Markdown spec according to http://daringfireball.net/projects/markdown/syntax or https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

I would suggest we make sure our markdown can move seamlessly between GitHub and being run through http://mixu.net/markdown-styles/ (with the --markdown template) without any authoring changes.

**Comment by nicklathe** [comment]
Ok, I'm cool with finding a better way. Currently REST-API-Basics.html does use ```. Here is the raw code: https://raw.githubusercontent.com/concur/developer.concur.com/preview/docs/guides/REST-API-Basics.markdown

**Comment by nicklathe** [comment]
Also, we are using Kramdown, not vanilla Markdown. Kramdown specifies the use of either a 4 space indent or ~~~ for code blocks.

**Comment by charlieconcur** [comment]
The original markdown for this document did not include ``` -- see https://raw.githubusercontent.com/retrosight/common/master/test.md -- so either a tool added the ``` or a human did so. Anybody know for certain it was a human?

Why did we pick Kramdown over vanilla Markdown?

**Comment by charlieconcur** [comment]
I'll let you know ahead of time I'm going to have a (very?) strong opinion about the use of and portability of Markdown over pretty much any other markup. :) :) :) <-- See my friendly smilies, and welcome to bashing of the dev portal as only a PM can do.

**Comment by howarddierking** [comment]
Vanilla markdown has very little functionality wrt code beyond the very basics. We went with kramdown because the kramdown processor is very fast (remember that markdown is not a compiler - just a format) - it also has more support, as mentioned, for syntax highlighting.

In any event, @nicklathe is investigating the right go forward approach - so let's defer the discussion until he comes back with a recommendation.

**Comment by howarddierking** [comment]
@charlieconcur I recommend a bit if open-handedness wrt "pure" markdown. Had we held purity as the significant bit, we would have HTML tables embedded in our markdown files.

**Comment by charlieconcur** [comment]
If it is with an open hand is it then: smackdown? ( Sorry, could not resist. I did try to do so! )

I don't think I'm making a purity argument. (Checks himself mentally and philosophically.) Nope, not a purity thing. I believe I am preferring Markdown for the following reasons:

* It is the lingua franca of GitHub documentation.
* It is portable **and** readable without changes across...
    * our site such as http://preview.developer.concur.com/docs/guides/REST-API-Basics.html and
    * in GitHub such as https://github.com/concur/receipt-service/wiki/REST-API-Basics (wiki) or https://github.com/retrosight/common/blob/master/test.md (source) and
    * editable in a GUI tool such as Mou http://25.io/mou/ and
    * consumable by a tool such as http://mixu.net/markdown-styles/ which outputs something easily sent to an (early adopter) customer.

I did spend some time reading through the differences between Markdown and Kramdown at http://kramdown.gettalong.org/syntax.html -- I believe the above outweighs the enhancements we see in Kramdown.

**Comment by howarddierking** [comment]
> It is the lingua franca of GitHub documentation

Actually, this is not true - https://help.github.com/articles/github-flavored-markdown/. You may also notice that GitHub prefers backticks for code highlighting

> It is portable and readable without changes

This isn't really true either - it depends on what is parsing the markdown. As I mentioned, basic markdown leaves out a lot (for good reason - it was trying to avoid becoming latex or ascidoc). We've gone far by aligning closely to GitHub's superset of markdown and for the features we get, this is worth the tradeoff of using syntax beyond the basic http://daringfireball.net/projects/markdown/. It's interesting that you mention editors - this is where you'll see all sorts of discrepancies - and this is because, again, there is not universal agreement beyond the basic definition. 

It is worth looking into the mixu tool you mentioned, but based on the evidence above, I don't find a compelling reason at this point to change our current course.

**Comment by howarddierking** [comment]
I'll also mention that GitHub uses Kramdown for its own docs site (as well is in how it processes GitHub pages/wikis) - https://github.com/github/developer.github.com/blob/master/Gemfile

**Comment by howarddierking** [comment]
Reviewed the page again post this afternoon's changes - everything looks good for this page now.
