### ISSUE TITLE
broken links pointing to api-reference/authentication/authentication.html

### ISSUE THREAD

**Issue by mattharrington001** [concur/developer.concur.com#765]
Since a PROD deployment this afternoon there are 28 broken links pointing to api-reference/authentication/authentication.html

URL        "/api-reference/authentication/authentication.html#web"
Name       "here"
Parent URL https://developer.concur.com/api-reference/index.html, line 4094, col 59

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#revoke-single-access-token"
Name       "revoked token messages"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2291, col 72

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#refreshing-access-token"
Name       "refresh the Concur authentication token"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2290, col 47

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#native"
Name       "Native Flow"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2289, col 65

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#refreshing-access-token"
Name       "refresh the Concur authentication token"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1812, col 47

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#revoke-single-access-token"
Name       "disconnect"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1811, col 47

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#access-tokens"
Name       "connect your users to and from"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1810, col 47

URL        "https://developer.concur.com/api-reference/authentication/authentication.html"
Name       "App Center flow"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1809, col 65

URL        "https://developer.concur.com/api-reference/authentication/authentication.html#web"
Name       "here"
Parent URL https://developer.concur.com/api-guides/travel/get-itinerary.html, line 2314, col 45

URL        "https://developer.concur.com/api-reference/authentication/authentication.html"
Name       "Oath 2.0 process"
Parent URL https://developer.concur.com/api-guides/travel/get-itinerary.html, line 2278, col 18

URL        "https://developer.concur.com/api-reference/authentication/authentication.html"
Name       "Oath 2.0 process"
Parent URL https://developer.concur.com/api-guides/travel/new-itinerary-manual.html, line 2280, col 22

URL        "https://developer.concur.com/api-reference/authentication/authentication.html"
Name       "link"
Parent URL https://developer.concur.com/changelog/2016/11/04/authentication-deprecation.html, line 353, col 270

URL        "/api-reference/authentication/authentication.html#native"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63

URL        "/api-reference/authentication/authentication.html#web"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59

URL        "/api-reference/authentication/authentication.html#native"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63

URL        "/api-reference/authentication/authentication.html#web"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59

URL        "/api-reference/authentication/authentication.html#native"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63

URL        "/api-reference/authentication/authentication.html#web"
Name       "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59

URL        "/api-reference/authentication/authentication.html"
Name       "Authentication"
Parent URL https://developer.concur.com/api-reference/callouts/post-fetch-attendee.html, line 4970, col 83

URL        "/api-reference/authentication/authentication.html"
Name       "Authentication"
Parent URL https://developer.concur.com/api-reference/callouts/post-list-search-request.html, line 4967, col 73

URL        "/api-reference/authentication/authentication.html"
Name       "Get Access Token using Native Flow"
Parent URL https://developer.concur.com/api-reference/callouts/request-validation.html, line 5085, col 108

URL        "/api-reference/authentication/authentication.html"
Name       "Get Access Token using Native Flow"
Parent URL https://developer.concur.com/api-reference/callouts/request-validation.html, line 5085, col 411

URL        "/api-reference/authentication/authentication.html#web"
Name       "Web authorization flow"
Parent URL https://developer.concur.com/api-reference/travel-profile/00-profile-services.html, line 4976, col 368

URL        "/api-reference/authentication/authentication.html#web"
Name       "Web authorization flow"
Parent URL https://developer.concur.com/api-reference/travel-profile/00-profile-services.html, line 4982, col 519

URL        "/api-reference/authentication/authentication.html#web"
Name       "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/04-notification-company-resource.html, line 5093, col 118

URL        "/api-reference/authentication/authentication.html#web"
Name       "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 4999, col 118

URL        "/api-reference/authentication/authentication.html#web"
Name       "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 5095, col 118

URL        "/api-reference/authentication/authentication.html#web"
Name       "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 5132, col 118

**Comment by henryyamamoto-concur** [comment]
URL "/api-reference/authentication/authentication.html#web"
Name "here"
Parent URL https://developer.concur.com/api-reference/index.html, line 4094, col 59
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#revoke-single-access-token"
Name "revoked token messages"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2291, col 72
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#refreshing-access-token"
Name "refresh the Concur authentication token"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2290, col 47
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#native"
Name "Native Flow"
Parent URL https://developer.concur.com/api-guides/ERP-integration/erp-integration.html, line 2289, col 65
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#refreshing-access-token"
Name "refresh the Concur authentication token"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1812, col 47
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#revoke-single-access-token"
Name "disconnect"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1811, col 47
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#access-tokens"
Name "connect your users to and from"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1810, col 47
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html"
Name "App Center flow"
Parent URL https://developer.concur.com/api-guides/e-receipts.html, line 1809, col 65
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html#web"
Name "here"
Parent URL https://developer.concur.com/api-guides/travel/get-itinerary.html, line 2314, col 45
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html"
Name "Oath 2.0 process"
Parent URL https://developer.concur.com/api-guides/travel/get-itinerary.html, line 2278, col 18
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html"
Name "Oath 2.0 process"
Parent URL https://developer.concur.com/api-guides/travel/new-itinerary-manual.html, line 2280, col 22
**FIXED: Pointed to new docs**

URL "https://developer.concur.com/api-reference/authentication/authentication.html"
Name "link"
Parent URL https://developer.concur.com/changelog/2016/11/04/authentication-deprecation.html, line 353, col 270
**FIXED: Pointed to new docs**

URL "/api-reference/authentication/authentication.html#native"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html#web"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html#native"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html#web"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html#native"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4088, col 63
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html#web"
Name "here"
Parent URL https://developer.concur.com/api-reference/, line 4094, col 59
**FIXED: REMOVED WHOLE SECTION AS IT HAD SEVERAL OTHER BROKEN LINKS**

URL "/api-reference/authentication/authentication.html"
Name "Authentication"
Parent URL https://developer.concur.com/api-reference/callouts/post-fetch-attendee.html, line 4970, col 83
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html"
Name "Authentication"
Parent URL https://developer.concur.com/api-reference/callouts/post-list-search-request.html, line 4967, col 73
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html"
Name "Get Access Token using Native Flow"
Parent URL https://developer.concur.com/api-reference/callouts/request-validation.html, line 5085, col 108
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html"
Name "Get Access Token using Native Flow"
Parent URL https://developer.concur.com/api-reference/callouts/request-validation.html, line 5085, col 411
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "Web authorization flow"
Parent URL https://developer.concur.com/api-reference/travel-profile/00-profile-services.html, line 4976, col 368
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "Web authorization flow"
Parent URL https://developer.concur.com/api-reference/travel-profile/00-profile-services.html, line 4982, col 519
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/04-notification-company-resource.html, line 5093, col 118
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 4999, col 118
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 5095, col 118
**FIXED: POINTED TO NEW URL**

URL "/api-reference/authentication/authentication.html#web"
Name "OAuth 2.0 Web flow authorization process"
Parent URL https://developer.concur.com/api-reference/travel-profile/05-notification-user-resource.html, line 5132, col 118
**FIXED: POINTED TO NEW URL**
