### ISSUE TITLE
Redirect mechanism

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#773]
We need an easier way (e.g. A UI with fields admins can self-serve or front matter driven) to enable redirects of pages. Some pages may be replaced with a new page or moved in such a way that requires a redirect.

**Comment by bhague1281** [comment]
Added JekyllRedirectFrom in #775 and #776 

Instructions on adding redirects here: https://github.com/concur/developer.concur.com/wiki/Adding-Redirects
