### ISSUE TITLE
register.html Website field should not require http/https

### ISSUE THREAD

**Issue by mrwanny** [concur/developer.concur.com#78]
on page http://preview.developer.concur.com/manage-apps/register.html
the Website field returns Please enter a valid URL when the input is www.sap.com

Mac OS 10.10.5
Chrome Version 44.0.2403.155 (64-bit)
it should be more forgiving and not expecting http/https

**Comment by henryyamamoto-concur** [comment]
Agreed. This is some weird limitation on the Eloqua side, which will be going away in November. We will need to redo forms then.

Also, @nicklathe put in prompts in the fields to help users better understand the expectations of the fields.
