### ISSUE TITLE
register.html "Before You Start" instructions difficult to notice

### ISSUE THREAD

**Issue by mrwanny** [concur/developer.concur.com#79]
I noticed the "Before You Start" instruction only after successfully registering when the following message appear stating:
```
Thank you. Your request was successfully submitted
Before You Start
- Use an email that is not in use in any Concur products, or is an existing Concur email—the address must be unique.
```
 
Mac OS 10.10.5
Chrome Version 44.0.2403.155 (64-bit)
probably putting the "Before You Start" instruction on the top of the page will make it easier for the user to read them before submitting the form

**Comment by henryyamamoto-concur** [comment]
Will update when UX resource is assigned to our team. Will look at these tool forms top to bottom then. Closing for now.
