### ISSUE TITLE
General layout and asset clean up

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#82]
Clean up layout and buttons on the following pages:

http://preview.developer.concur.com/why-concur.html

- [x] Make buttons one, consistent size
- [x] Make "Travel Suppliers" section blue background, change button to default instead of blue

http://preview.developer.concur.com/manage-apps/go-to-market.html

- [x] Fix font size as shown below:
![screen shot 2015-10-06 at 9 40 56 am](https://cloud.githubusercontent.com/assets/8781478/10317049/51d14bc2-6c17-11e5-984f-15f011b39737.png)

Other tweaks as you see fit.

**Comment by nicklathe** [comment]
@henryyamamoto-concur Couple questions:

1. Do you mean you want all of these buttons on these two pages the same width? That will look pretty weird. The "view" buttons are much smaller, and stretching them out would look weird.
2. Last check box says fix font size. Do you want that line with the asterisk smaller?

**Comment by henryyamamoto-concur** [comment]
1. You'll notice the "contact us" button on the top and bottom are of a different size. So not necessarily same size, but same style? The button sizes on the other "Go to Market" page are fine as is.

2. The last one is just making it a smaller point size.

**Comment by nicklathe** [comment]
Ah I see now with the buttons. I had fixed it already locally, and wasn't seeing the difference. Just checked out livesite and see now.
