### ISSUE TITLE
update App Submission form with attached doc

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#833]
Please replace the App Submission form on the Dev Center (Manage Apps tab\App Certification)
with the one attached to this ticket.

thanks - Doug
[Concur_Application_Submission_Form_v4a-12-27-16.docx](https://github.com/concur/developer.concur.com/files/673587/Concur_Application_Submission_Form_v4a-12-27-16.docx)

**Comment by bhague1281** [comment]
#850

**Comment by dstaab** [comment]
what is the issue you want me to fix?  This GitHub UI blows.

**Comment by bhague1281** [comment]
The above is a reference to the PR with the change. We should have the new form pushed to livesite today. No action required on your part.
