### ISSUE TITLE
Broken links in PROD

### ISSUE THREAD

**Issue by mattharrington001** [concur/developer.concur.com#846]
There are 2 broken links in PROD right now. These started sometime Dec. 20th/21st. 

Fixes aren't clear to me. Seems related to the recent changes moving things around.

**Parent URL:** https://developer.concur.com/api-reference-deprecated/version-one-one/expense-entry-attendee/expense-entry-attendee-resource-post.html
**Broken link:** https://developer.concur.com/node/205 
**Broken link text:** ‘HTTP Status Codes’

**Parent URL:** https://developer.concur.com/api-reference-deprecated/version-one/Image/image-resource-entry-image-URL-get.html
**Broken link:** https://developer.concur.com/api-reference/expense/expense-report/expense-form-resource/expense-form-resource-get.html
**Broken link text:** ‘Get Report Details’

**Comment by bhague1281** [comment]
Looks like these links have been broken long before those dates.

@henryyamamoto-concur Can you find the appropriate pages to fix these links?

**Comment by bhague1281** [comment]
Fixed #884
