### ISSUE TITLE
Add broken link and image checking to CI build

### ISSUE THREAD

**Issue by bhague1281** [concur/developer.concur.com#848]
Currently, we're detecting broken links weeks or months down the road. Let's automate this with [html-proofer](https://github.com/gjtorikian/html-proofer)

**Comment by mattharrington001** [comment]
Technically, we detect broken links the next day on PROD. I was just out for xmas vacay so the broken links in the latest bug were a few weeks old.

But yes, we should add broken link checking to the CI gates. You can ping me to steal the approach the test team put together for a jump start if you'd like.

**Comment by bhague1281** [comment]
#1068
