### ISSUE TITLE
Concur Sandbox Error

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#852]
1. Go to: https://developer.concur.com/manage-apps/register.html
2. Complete required fields and submit form
3. "Please wait" message appears
4. After message the error below appears.

Error Appearing:

Error (Critical): <?xml version="1.0" encoding="UTF-8"?> <Request><Header><Version>1.0</Version><Log><Level>None</Level></Log><TravelerUID>1</TravelerUID><ExpenseUID>0</ExpenseUID><LoginID>wsuser@concur.com</LoginID><EntityID></EntityID><CompanyID></CompanyID><SUVersion>134.0</SUVersion><CteMtRequestId>1/4/2017-80495.79</CteMtRequestId></Header> <Body><Action> <CreateExpenseCompany><EntityCode>d</EntityCode><CompanyName>Test Company</CompanyName><OuttaskCompanyId></OuttaskCompanyId><ConfigurationName></ConfigurationName><ProdOffering>DIRECT-BREEZE+</ProdOffering><ClientGuid></ClientGuid><ContactCuuid>0</ContactCuuid><IntuitRealmId></IntuitRealmId><IntuitAppDbId></IntuitAppDbId><SalesforceOrgId></SalesforceOrgId><IsGlobalTemplate></IsGlobalTemplate><EnableInvoice>N</EnableInvoice><IntelligenceType></IntelligenceType><ActiveCountries>US,GB,AU,CA</ActiveCountries><DefaultCountry>US</DefaultCountry></CreateExpenseCompany> </Action></Body></Request> <?xml version="1.0" encoding="UTF-8"?> <ces_error> <request><![CDATA[<?xml version="1.0" encoding="UTF-8"?> <Request><Header><Version>1.0</Version><Log><Level>None</Level></Log><TravelerUID>1</TravelerUID><ExpenseUID>0</ExpenseUID><LoginID>wsuser@concur.com</LoginID><EntityID></EntityID><CompanyID></CompanyID><SUVersion>134.0</SUVersion><CteMtRequestId>1/4/2017-80495.79</CteMtRequestId></Header> <Body><Action> <CreateExpenseCompany><EntityCode>d</EntityCode><CompanyName>Test Company</CompanyName><OuttaskCompanyId></OuttaskCompanyId><ConfigurationName></ConfigurationName><ProdOffering>DIRECT-BREEZE+</ProdOffering><ClientGuid></ClientGuid><ContactCuuid>0</ContactCuuid><IntuitRealmId></IntuitRealmId><IntuitAppDbId></IntuitAppDbId><SalesforceOrgId></SalesforceOrgId><IsGlobalTemplate></IsGlobalTemplate><EnableInvoice>N</EnableInvoice><IntelligenceType></IntelligenceType><ActiveCountries>US,GB,AU,CA</ActiveCountries><DefaultCountry>US</DefaultCountry></CreateExpenseCompany> </Action></Body></Request>]]></request> <ces> <entity_code></entity_code> <cuuid/> <is_expense_multi_tenant></is_expense_multi_tenant> </ces> <error time="2017-04-01 19:22:25" timezone="America/Vancouver"> <error_source>java.lang.RuntimeException</error_source> <error_code></error_code> <error_description><![CDATA[java.sql.SQLException: The query has timed out.]]></error_description> <error_root_cause><![CDATA[SQLException: The query has timed out.]]></error_root_cause> <stack_trace><![CDATA[java.lang.RuntimeException: java.sql.SQLException: The query has timed out. at com.concur.midtier.services.companycreate.DefaultCompanyCreateService.createAndSetupMtEntity(DefaultCompanyCreateService.java:60) at com.concur.midtier.webservices.xmlhttp.actions.companycreate.CreateExpenseCompany.invoke(CreateExpenseCompany.java:38) at com.concur.midtier.webservices.xmlhttp.message.GenericMessageBroker.invoke(GenericMessageBroker.java:280) at com.concur.midtier.webservices.xmlhttp.message.GenericMessageBroker.synchronousMessage(GenericMessageBroker.java:46) at com.concur.midtier.webservices.xmlhttp.servlets.ReqRespMessageListener.doPost(ReqRespMessageListener.java:369) at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) at com.concur.midtier.webservices.xmlhttp.servlets.ReqRespMessageListener.service(ReqRespMessageListener.java:312) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:221) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620) at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2453) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: java.sql.SQLException: The query has timed out. at net.sourceforge.jtds.jdbc.TdsCore.wait(TdsCore.java:3936) at net.sourceforge.jtds.jdbc.TdsCore.executeSQL(TdsCore.java:1046) at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:537) at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:561) at com.concur.midtier.datasource.DebuggingPreparedStatement.execute(DebuggingPreparedStatement.java:60) at com.concur.midtier.data.dao.util.DBUtils.runProcWithOutputParameters(DBUtils.java:173) at com.concur.midtier.data.dao.ibatis.HostDAOImpl.createVdb(HostDAOImpl.java:2158) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.ibatis.dao.engine.impl.DaoProxy.invoke(DaoProxy.java:72) at com.sun.proxy.$Proxy332.createVdb(Unknown Source) at com.concur.midtier.services.companycreate.DefaultCompanyCreateService.createVdb(DefaultCompanyCreateService.java:82) at com.concur.midtier.services.companycreate.DefaultCompanyCreateService.createAndSetupMtEntity(DefaultCompanyCreateService.java:48) ... 27 more ]]></stack_trace> <category>Other</category> <subcategory>DefaultCompanyCreateService</subcategory> </error> <server> <name>seapr1emt614.concurasp.com</name> </server> <application> <name>CESMidTier</name> <prod_status>prod</prod_status> <midtier_server></midtier_server> </application> <message><![CDATA[null]]></message> <server_variables> <param name="SERVER_NAME">seapr1emt614.concurasp.com</param> <param name="LOCAL_ADDR"></param> <param name="REMOTE_ADDR">10.205.12.41</param> <param name="REQUEST_METHOD">POST</param> <param name="SCRIPT_NAME">CreateExpenseCompany</param> </server_variables> <expense_db></expense_db> <company id=""/> <user id="1"> <login_id>wsuser@concur.com</login_id> </user> <cliqbook> <record_locator></record_locator> </cliqbook> </ces_error>

**Comment by bhague1281** [comment]
Sandbox is back up. #870
