### ISSUE TITLE
Need to hide the ability to create a sandbox on the developer.concur.com site

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#894]
1.  Need to hide the button on the main developer.concur.com page.  This button should be replaced with a button that links to the Change Log.
2.  The "Manage Apps/Sandbox" link should be modified to go to an informational page about who should request sandboxes and guidance as to who to go to for the link to create one
3.  The actual sandbox creation url should be left intact, so that internal Concur teams can point authorized users to it to create their sandboxes.
4.  If possible, the sandbox creation url should be hidden from searches on the developer.concur.com site, to make it less likely that non-authorized developers can't find the url and create a sandbox

**Comment by elhansen748** [comment]
[Sandboxregistrationrules.docx](https://github.com/concur/developer.concur.com/files/758716/Sandboxregistrationrules.docx)

**Comment by elhansen748** [comment]
Hey Brian, added the wording for the page that users should see when they go to the Manage Apps/sandbox link.  Want to chat with you tomorrow on how the page should be formatted on the dev site.

**Comment by bhague1281** [comment]
- [ ] Add new content to current sandbox page
- [ ] Create new page with the current sandbox form
- [ ] Remove new page from Google custom search

**Comment by bhague1281** [comment]
Waiting on feedback from business development and marketing.
