### ISSUE TITLE
Broken link on http://preview.developer.concur.com/api-reference/callouts/event-notification.html

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#94]
on http://preview.developer.concur.com/api-reference/callouts/event-notification.html
under the section 

Additional Information

The links: 
Installation Process http://preview.developer.concur.com/callouts/event-notification#installproc
Responses and Errors http://preview.developer.concur.com/callouts/event-notification#responses

Give 404 errors

**Comment by henryyamamoto-concur** [comment]
Fixed
