### ISSUE TITLE
Font size is inconsistent onhttp://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#97]
Font size is inconsistent onhttp://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html

10.5pts and 11pts

**Comment by henryyamamoto-concur** [comment]
Dupe of #83

**Comment by henryyamamoto-concur** [comment]
Fixed with afcd21d4374488439b4e7e43aba97a49dd17507c
