### ISSUE TITLE
Link goes to the old dev portal on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html 

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#98]
Core Concepts on http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html  links to the oldf dev portal https://developer.concur.com/node/25#co

**Comment by howarddierking** [comment]
@henryyamamoto-concur - if you want this scheduled for the current sprint, please make sure to set the milestone.

**Comment by henryyamamoto-concur** [comment]
@howarddierking  Fixed this one when I did a sweep of the Callout section.

Items in the backlog can be pulled into the current sprint as time permits. Those have already been triaged. Those in new have not.
