### ISSUE TITLE
API - Callouts - Fetch Attendee Version 2 Callout - Links to Drupal

### ISSUE THREAD

**Issue by dustingraves** [concur/developer.concur.com#99]
http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html

Bottom of first bullet point:
It uses an outbound message where Expense calls a public facing API endpoint provided by the application connector.
Refer to Callouts > Core Concepts for more information.
ALSO
 down the page at "Concur Connect Callout Details"
Information on how to download, install, and configure the application connector is included in Callouts > Core Concepts.

BAD LINK
https://developer.concur.com/node/25#co

ANOTHER
Fetch Attendee Process Overview> Functions> Version 2.0: Post Attendee Search Request

BAD LINK
https://developer.concur.com/callouts/fetch-attendee/post-fetch-attendee

**Comment by henryyamamoto-concur** [comment]
http://preview.developer.concur.com/api-reference/callouts/fetch-attendee.html
